/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Scales`; params?: Router.UnknownInputParams; } | { pathname: `/ScalesDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Training`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/RoutineBuilder`; params?: Router.UnknownInputParams; } | { pathname: `/Chords`; params?: Router.UnknownInputParams; } | { pathname: `/Notes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Scales`; params?: Router.UnknownOutputParams; } | { pathname: `/ScalesDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/Training`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/RoutineBuilder`; params?: Router.UnknownOutputParams; } | { pathname: `/Chords`; params?: Router.UnknownOutputParams; } | { pathname: `/Notes`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/Scales${`?${string}` | `#${string}` | ''}` | `/ScalesDetails${`?${string}` | `#${string}` | ''}` | `/Training${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/RoutineBuilder${`?${string}` | `#${string}` | ''}` | `/Chords${`?${string}` | `#${string}` | ''}` | `/Notes${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Scales`; params?: Router.UnknownInputParams; } | { pathname: `/ScalesDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Training`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/RoutineBuilder`; params?: Router.UnknownInputParams; } | { pathname: `/Chords`; params?: Router.UnknownInputParams; } | { pathname: `/Notes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
