// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Server.Models;

public partial class Enharmonic
{
    public int EnharmonicId { get; set; }

    public string EnharmonicName { get; set; } = null!;
    [JsonIgnore]
    public virtual ICollection<Note> Notes { get; set; } = new List<Note>();
}