// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Models;

public partial class ExerciseNote
{
    public int ScaleExerciseId { get; set; }

    public int NoteId { get; set; }

    public int NoteOrderNumber { get; set; }

    public virtual Note Note { get; set; } = null!;

    public virtual ScaleExercise ScaleExercise { get; set; } = null!;
}