// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Server.Models;

public partial class Key
{
    public int KeyId { get; set; }

    public string KeyName { get; set; } = null!;

    public int? KeyFlatsCount { get; set; }

    public int? KeyDoubleFlatsCount { get; set; }

    public int? KeyDoubleSharpsCount { get; set; }

    public string? KeyRelativeMinor { get; set; }

    public string? KeyRelativeMajor { get; set; }

    public int? KeySharpsCount { get; set; }

    public string KeyQuality { get; set; } = null!;
    [JsonIgnore]
    public virtual ICollection<Scale> Scales { get; set; } = new List<Scale>();
}