// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Server.Models;

public partial class Note
{
    public int NoteId { get; set; }

    public string NoteName { get; set; } = null!;
    [JsonIgnore]
    public virtual ICollection<ExerciseNote> ExerciseNotes { get; set; } = new List<ExerciseNote>();
    [JsonIgnore]
    public virtual ICollection<Interval> IntervalIntervalNotes { get; set; } = new List<Interval>();
    [JsonIgnore]
    public virtual ICollection<Interval> IntervalRootNotes { get; set; } = new List<Interval>();
    [JsonIgnore]
    public virtual ICollection<Sound> Sounds { get; set; } = new List<Sound>();
    [JsonIgnore]
    public virtual ICollection<Enharmonic> Enharmonics { get; set; } = new List<Enharmonic>();
}