// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Server.Models;

public partial class Routine
{
    public int RoutineId { get; set; }

    public string RoutineName { get; set; } = null!;

    public int? RoutineExerciseCount { get; set; }

    public int? RoutineTimeToGuess { get; set; }

    public string? RoutineDescription { get; set; }

    [JsonIgnore]
    public virtual ICollection<SERoutine> SERoutines { get; set; } = new List<SERoutine>();
    [JsonIgnore]
    public virtual ICollection<ScaleExercise> ScaleExercises { get; set; } = new List<ScaleExercise>();
}