// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Server.Models;

public partial class ScaleExercise
{
    public int ScaleExerciseId { get; set; }

    public string ListeningMode { get; set; } = null!;

    public int? TimePerNote { get; set; }

    public int? NumberOfNotes { get; set; }

    public int? NumberOfOctaves { get; set; }

    public int? ScaleId { get; set; }
    [JsonIgnore]
    public virtual ICollection<ExerciseNote> ExerciseNotes { get; set; } = new List<ExerciseNote>();
    [JsonIgnore]
    public virtual Scale? Scale { get; set; }
    [JsonIgnore]
    public virtual ICollection<Routine> Routines { get; set; } = new List<Routine>();
    [JsonIgnore]
    public virtual ICollection<SERoutine> SERoutines { get; set; } = new HashSet<SERoutine>();
}