// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Server.Models;

public partial class Scale
{
    public int ScaleId { get; set; }

    public string ScaleName { get; set; } = null!;

    public string ScaleQuality { get; set; } = null!;

    public string ScaleRoot { get; set; } = null!;

    public int? KeyId { get; set; }

    public virtual Key? Key { get; set; }
    [JsonIgnore]
    public virtual ICollection<ScaleExercise> ScaleExercises { get; set; } = new List<ScaleExercise>();
    [JsonIgnore]
    public virtual ICollection<Interval> Intervals { get; set; } = new List<Interval>();

    [JsonIgnore]
    public virtual ICollection<ScaleNote> ScaleNotes { get; set; } = new HashSet<ScaleNote>();
}