// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Models;

public partial class Sound
{
    public int SoundId { get; set; }

    public string? SoundFilePath { get; set; }

    public int SoundOctave { get; set; }

    public int NoteId { get; set; }

    public virtual Note Note { get; set; } = null!;
}