export default class Sound {
    id!: number;
    filePath!: string | null;
    octave!: number;
    noteId!: number;

    constructor(id: number, filePath: string | null, octave: number, noteId: number) {
        this.id = id;
        this.filePath = filePath;
        this.octave = octave;
        this.noteId = noteId;
    }
}

export const Sounds = {
    "A-1": require("@/assets/audio/A-1.mp3"),
    "AS-1": require("@/assets/audio/AS-1.mp3"),
    "B-1": require("@/assets/audio/B-1.mp3"),

    "C0": require("@/assets/audio/C0.mp3"),
    "CS0": require("@/assets/audio/CS1.mp3"),
    "D0": require("@/assets/audio/D0.mp3"),
    "DS0": require("@/assets/audio/DS0.mp3"),
    "E0": require("@/assets/audio/E0.mp3"),
    "F0": require("@/assets/audio/F0.mp3"),
    "FS0": require("@/assets/audio/FS0.mp3"),
    "G0": require("@/assets/audio/G0.mp3"),
    "GS0": require("@/assets/audio/GS0.mp3"),
    "A0": require("@/assets/audio/A0.mp3"),
    "AS0": require("@/assets/audio/AS0.mp3"),
    "B0": require("@/assets/audio/B0.mp3"),

    "C1": require("@/assets/audio/C1.mp3"),
    "CS1": require("@/assets/audio/CS1.mp3"),
    "D1": require("@/assets/audio/D1.mp3"),
    "DS1": require("@/assets/audio/DS1.mp3"),
    "E1": require("@/assets/audio/E1.mp3"),
    "F1": require("@/assets/audio/F1.mp3"),
    "FS1": require("@/assets/audio/FS1.mp3"),
    "G1": require("@/assets/audio/G1.mp3"),
    "GS1": require("@/assets/audio/GS1.mp3"),
    "A1": require("@/assets/audio/A1.mp3"),
    "AS1": require("@/assets/audio/AS1.mp3"),
    "B1": require("@/assets/audio/B1.mp3"),

    "C2": require("@/assets/audio/C2.mp3"),
    "CS2": require("@/assets/audio/CS2.mp3"),
    "D2": require("@/assets/audio/D2.mp3"),
    "DS2": require("@/assets/audio/DS2.mp3"),
    "E2": require("@/assets/audio/E2.mp3"),
    "F2": require("@/assets/audio/F2.mp3"),
    "FS2": require("@/assets/audio/FS2.mp3"),
    "G2": require("@/assets/audio/G2.mp3"),
    "GS2": require("@/assets/audio/GS2.mp3"),
    "A2": require("@/assets/audio/A2.mp3"),
    "AS2": require("@/assets/audio/AS2.mp3"),
    "B2": require("@/assets/audio/B2.mp3"),

    "C3": require("@/assets/audio/C3.mp3"),
    "CS3": require("@/assets/audio/CS3.mp3"),
    "D3": require("@/assets/audio/D3.mp3"),
    "DS3": require("@/assets/audio/DS3.mp3"),
    "E3": require("@/assets/audio/E3.mp3"),
    "F3": require("@/assets/audio/F3.mp3"),
    "FS3": require("@/assets/audio/FS3.mp3"),
    "G3": require("@/assets/audio/G3.mp3"),
    "GS3": require("@/assets/audio/GS3.mp3"),
    "A3": require("@/assets/audio/A3.mp3"),
    "AS3": require("@/assets/audio/AS3.mp3"),
    "B3": require("@/assets/audio/B3.mp3"),

    "C4": require("@/assets/audio/C4.mp3"),
    "CS4": require("@/assets/audio/CS4.mp3"),
    "D4": require("@/assets/audio/D4.mp3"),
    "DS4": require("@/assets/audio/DS4.mp3"),
    "E4": require("@/assets/audio/E4.mp3"),
    "F4": require("@/assets/audio/F4.mp3"),
    "FS4": require("@/assets/audio/FS4.mp3"),
    "G4": require("@/assets/audio/G4.mp3"),
    "GS4": require("@/assets/audio/GS4.mp3"),
    "A4": require("@/assets/audio/A4.mp3"),
    "AS4": require("@/assets/audio/AS4.mp3"),
    "B4": require("@/assets/audio/B4.mp3"),

    "C5": require("@/assets/audio/C5.mp3"),
    "CS5": require("@/assets/audio/CS5.mp3"),
    "D5": require("@/assets/audio/D5.mp3"),
    "DS5": require("@/assets/audio/DS5.mp3"),
    "E5": require("@/assets/audio/E5.mp3"),
    "F5": require("@/assets/audio/F5.mp3"),
    "FS5": require("@/assets/audio/FS5.mp3"),
    "G5": require("@/assets/audio/G5.mp3"),
    "GS5": require("@/assets/audio/GS5.mp3"),
    "A5": require("@/assets/audio/A5.mp3"),
    "AS5": require("@/assets/audio/AS5.mp3"),
    "B5": require("@/assets/audio/B5.mp3"),

    "C6": require("@/assets/audio/C6.mp3"),
    "CS6": require("@/assets/audio/CS6.mp3"),
    "D6": require("@/assets/audio/D6.mp3"),
    "DS6": require("@/assets/audio/DS6.mp3"),
    "E6": require("@/assets/audio/E6.mp3"),
    "F6": require("@/assets/audio/F6.mp3"),
    "FS6": require("@/assets/audio/FS6.mp3"),
    "G6": require("@/assets/audio/G6.mp3"),
    "GS6": require("@/assets/audio/GS6.mp3"),
    "A6": require("@/assets/audio/A6.mp3"),
    "AS6": require("@/assets/audio/AS6.mp3"),
    "B6": require("@/assets/audio/B6.mp3"),

    "C7": require("@/assets/audio/C7.mp3")
}

export function selectSound(soundName: string) {
    const soundArray = {
        'A-1': Sounds["A-1"],
        'AS-1': Sounds["AS-1"],
        'B-1': Sounds["B-1"],

        'C0': Sounds.C0,
        'CS0': Sounds.CS0,
        'D0': Sounds.D0,
        'DS0': Sounds.DS0,
        'E0': Sounds.E0,
        'F0': Sounds.F0,
        'FS0': Sounds.FS0,
        'G0': Sounds.G0,
        'GS0': Sounds.GS0,
        'A0': Sounds.A0,
        'AS0': Sounds.AS0,
        'B0': Sounds.B0,

        'C1': Sounds.C1,
        'CS1': Sounds.CS1,
        'D1': Sounds.D1,
        'DS1': Sounds.DS1,
        'E1': Sounds.E1,
        'F1': Sounds.F1,
        'FS1': Sounds.FS1,
        'G1': Sounds.G1,
        'GS1': Sounds.GS1,
        'A1': Sounds.A1,
        'AS1': Sounds.AS1,
        'B1': Sounds.B1,

        'C2': Sounds.C2,
        'CS2': Sounds.CS2,
        'D2': Sounds.D2,
        'DS2': Sounds.DS2,
        'E2': Sounds.E2,
        'F2': Sounds.F2,
        'FS2': Sounds.FS2,
        'G2': Sounds.G2,
        'GS2': Sounds.GS2,
        'A2': Sounds.A2,
        'AS2': Sounds.AS2,
        'B2': Sounds.B2,

        'C3': Sounds.C3,
        'CS3': Sounds.CS3,
        'D3': Sounds.D3,
        'DS3': Sounds.DS3,
        'E3': Sounds.E3,
        'F3': Sounds.F3,
        'FS3': Sounds.FS3,
        'G3': Sounds.G3,
        'GS3': Sounds.GS3,
        'A3': Sounds.A3,
        'AS3': Sounds.AS3,
        'B3': Sounds.B3,

        'C4': Sounds.C4,
        'CS4': Sounds.CS4,
        'D4': Sounds.D4,
        'DS4': Sounds.DS4,
        'E4': Sounds.E4,
        'F4': Sounds.F4,
        'FS4': Sounds.FS4,
        'G4': Sounds.G4,
        'GS4': Sounds.GS4,
        'A4': Sounds.A4,
        'AS4': Sounds.AS4,
        'B4': Sounds.B4,

        'C5': Sounds.C5,
        'CS5': Sounds.CS5,
        'D5': Sounds.D5,
        'DS5': Sounds.DS5,
        'E5': Sounds.E5,
        'F5': Sounds.F5,
        'FS5': Sounds.FS5,
        'G5': Sounds.G5,
        'GS5': Sounds.GS5,
        'A5': Sounds.A5,
        'AS5': Sounds.AS5,
        'B5': Sounds.B5,

        'C6': Sounds.C6,
        'CS6': Sounds.CS6,
        'D6': Sounds.D6,
        'DS6': Sounds.DS6,
        'E6': Sounds.E6,
        'F6': Sounds.F6,
        'FS6': Sounds.FS6,
        'G6': Sounds.G6,
        'GS6': Sounds.GS6,
        'A6': Sounds.A6,
        'AS6': Sounds.AS6,
        'B6': Sounds.B6,

        'C7': Sounds.C7
    }

    // @ts-ignore
    return soundArray[soundName.split('.')[0]];
}