// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PopulationScript.Models;

public partial class Interval
{
    public int IntervalId { get; set; }

    public string IntervalQuality { get; set; } = null!;

    public int IntervalSize { get; set; }

    public int IntervalSemitonesFromRoot { get; set; }

    public int RootNoteId { get; set; }

    public int IntervalNoteId { get; set; }

    public virtual Note IntervalNote { get; set; } = null!;

    public virtual Note RootNote { get; set; } = null!;

    public virtual ICollection<Chord> Chords { get; set; } = new List<Chord>();

    public virtual ICollection<Scale> Scales { get; set; } = new List<Scale>();
}