// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PopulationScript.Models;

public partial class Key
{
    public int KeyId { get; set; }

    public string KeyName { get; set; } = null!;
    public string KeyQuality { get; set; } = null!;
    public int? KeyFlatsCount { get; set; }

    public int? KeySharpsCount { get; set; }

    public string? KeyRelativeMinor { get; set; }

    public string? KeyRelativeMajor { get; set; }

    public virtual ICollection<Scale> Scales { get; set; } = new List<Scale>();
}