// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PopulationScript.Models;

public partial class Note
{
    public int NoteId { get; set; }

    public string NoteName { get; set; } = null!;

    public string? NoteEnharmonic { get; set; }

    public virtual ICollection<Interval> IntervalIntervalNotes { get; set; } = new List<Interval>();

    public virtual ICollection<Interval> IntervalRootNotes { get; set; } = new List<Interval>();
}