// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PopulationScript.Models;

public partial class Scale
{
    public int ScaleId { get; set; }

    public string ScaleName { get; set; } = null!;

    public string ScaleQuality { get; set; } = null!;

    public string ScaleRoot { get; set; } = null!;

    public int? KeyId { get; set; }

    public virtual Key? Key { get; set; }

    public virtual ICollection<Interval> Intervals { get; set; } = new List<Interval>();
}